export const PLANS = {
  free: {
    name: 'Free Forever',
    price: { usa: 0, india: 0 },
    currency: { usa: 'USD', india: 'INR' },
    features: {
      orders_per_month: 10,
      whatsapp_path: 'shared' as const,
      ai_messaging: false,
      photo_enhancement: 'basic' as const,
      background_removal: false,
      broadcasts: false,
      ai_coach: false,
      instagram_publishing: false,
      analytics: 'basic' as const,
      inventory: true,
      cod: true,
      customer_portal: true,
    },
  },
  growth: {
    name: 'Growth',
    price: { usa: 19, india: 399 },
    currency: { usa: 'USD', india: 'INR' },
    features: {
      orders_per_month: null,
      whatsapp_path: 'virtual_dedicated' as const,
      ai_messaging: true,
      photo_enhancement: 'full' as const,
      background_removal: true,
      broadcasts: true,
      ai_coach: false,
      instagram_publishing: false,
      analytics: 'standard' as const,
      inventory: true,
      cod: true,
      customer_portal: true,
    },
  },
  pro: {
    name: 'Pro',
    price: { usa: 39, india: 799 },
    currency: { usa: 'USD', india: 'INR' },
    features: {
      orders_per_month: null,
      whatsapp_path: 'own_number' as const,
      ai_messaging: true,
      photo_enhancement: 'full' as const,
      background_removal: true,
      broadcasts: true,
      ai_coach: true,
      instagram_publishing: true,
      analytics: 'full' as const,
      inventory: true,
      cod: true,
      customer_portal: true,
    },
  },
} as const;

export type PlanId = keyof typeof PLANS;
