export type SellerStatus = 'aspiring' | 'onboarding' | 'active' | 'paused' | 'suspended';
export type FulfillmentMode = 'pickup' | 'self_delivery' | 'third_party_delivery';
export type WhatsAppPath = 'shared' | 'virtual_dedicated' | 'own_number';
export type Market = 'usa' | 'india' | 'canada';
export type Language = 'en' | 'hi' | 'es';

export interface Seller {
  id: string;
  user_id: string;
  business_name: string;
  slug: string;
  description: string | null;
  category: string;
  city: string;
  state: string | null;
  country: Market;
  language: Language;
  phone: string;
  email: string | null;
  status: SellerStatus;
  fulfillment_modes: FulfillmentMode[];
  pickup_address: string | null;
  delivery_radius_km: number | null;
  delivery_fee: number | null;
  whatsapp_path: WhatsAppPath;
  whatsapp_number: string | null;
  whatsapp_connected: boolean;
  instagram_connected: boolean;
  facebook_connected: boolean;
  stripe_account_id: string | null;
  razorpay_account_id: string | null;
  upi_id: string | null;
  avatar_url: string | null;
  cover_photo_url: string | null;
  story_text: string | null;
  video_url: string | null;
  phone_verified: boolean;
  photo_verified: boolean;
  orders_milestone: number;
  average_rating: number;
  is_active_seller: boolean;
  member_since: string;
  max_orders_per_day: number | null;
  max_orders_per_week: number | null;
  deposit_percentage: number;
  cod_enabled: boolean;
  auto_reply_enabled: boolean;
  plan: 'free' | 'growth' | 'pro';
  plan_expires_at: string | null;
  total_orders: number;
  total_revenue: number;
  on_time_percentage: number;
  expo_push_token: string | null;
  created_at: string;
  updated_at: string;
}
